services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#
#  web:
#    build:
#      context: ./app
#      dockerfile: Dockerfile
#    depends_on:
#      - db
#    environment:
#      DB_USER: myuser
#      DB_PASSWORD: mypassword
#      DB_HOST: db
#      DB_PORT: 5432
#      DB_NAME: mydb
#    ports:
 #     - "8000:8000"

volumes:
  postgres_data: