[app_settings]
app_port = 8000
app_host = "0.0.0.0"
app_version = "1.0.0"
app_name = "nbc-back"
#префикс для всех маршрутов приложения:
app_mount = "/api/v1"


[db_settings]
db_name = "postgres"
db_user ="myuser"
db_password = "mypassword"
db_host = "localhost"
db_port = 5432

[file_storage_settings]
root_dir = "~"
