[app_settings]
app_port = 8000
app_host = "127.0.0.1"
app_version = "1.0.0"
app_name = "NeoBitCloud_simple_file_storage"
#префикс для всех маршрутов приложения:
app_mount = "/api/v1"


[db_settings]
db_name = "storage_db"
db_user ="postgres"
db_password = "postgres"
db_host = "127.0.0.1"
db_port = 5432

[file_storage_settings]
root_dir = "C:\\Users\\novna\\OneDrive\\Рабочий стол\\"
