[app_settings]
app_port = 8000
app_host = "127.0.0.1"
app_version = "1.0.0"
app_name = "NeoBitCloud"
#префикс для всех маршрутов приложения:
app_mount = "/api/v1"
environment = "dev"



[db_settings]
db_name = "storage_db"
db_user ="postgres"
db_password = "postgres"
db_host = "127.0.0.1"
db_port = 5432

[file_storage_settings]
root_dir = "~"


[presigned_url_settings]
access_key = "AKIAIOSFODNN7EXAMPLE"
secret_key = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
expiration_minutes = 15
