[app_settings]
app_port = 8000
app_version = "0.0.1"
app_name = "s3_service"
app_host = "127.0.0.1"
app_mount = "/api/v1"


[db_settings]
db_name = "postgres"
db_user = "root"
db_password = "qwerty"
db_host = "localhost"
db_port = 5555