apiVersion: 1

datasources:
- name: PostgreSQL
  id: 1
  type: postgres
  url: db:5432 
  user: postgres
  secureJsonData:
    password: postgres
  jsonData:
    sslmode: "disable"
    database: "storage_db"