"""Update models

Revision ID: 826d78d7ec60
Revises: 3aa37e61e240
Create Date: 2024-12-24 01:12:14.420177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '826d78d7ec60'
down_revision: Union[str, None] = '3aa37e61e240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_id', table_name='file')
    op.drop_index('ix_file_url', table_name='file')
    op.drop_table('file')
    op.add_column('bucket', sa.Column('owner_name', sa.String(), nullable=False))
    op.add_column('bucket', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('bucket', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'bucket', 'user', ['owner_id'], ['id'])
    op.drop_column('bucket', 'owner')
    op.add_column('object', sa.Column('owner_name', sa.String(), nullable=False))
    op.add_column('object', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('object', sa.Column('bucket_name', sa.String(), nullable=False))
    op.add_column('object', sa.Column('bucket_id', sa.Integer(), nullable=True))
    op.add_column('object', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('object', sa.Column('extension', sa.String(), nullable=True))
    op.add_column('object', sa.Column('download_url', sa.String(), nullable=False))
    op.add_column('object', sa.Column('size', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'object', 'bucket', ['bucket_id'], ['id'])
    op.create_foreign_key(None, 'object', 'user', ['owner_id'], ['id'])
    op.drop_column('object', 'owner')
    op.drop_column('object', 'bucket')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('bucket', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('object', sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'object', type_='foreignkey')
    op.drop_constraint(None, 'object', type_='foreignkey')
    op.drop_column('object', 'size')
    op.drop_column('object', 'download_url')
    op.drop_column('object', 'extension')
    op.drop_column('object', 'updated_at')
    op.drop_column('object', 'bucket_id')
    op.drop_column('object', 'bucket_name')
    op.drop_column('object', 'owner_id')
    op.drop_column('object', 'owner_name')
    op.add_column('bucket', sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bucket', type_='foreignkey')
    op.drop_column('bucket', 'updated_at')
    op.drop_column('bucket', 'owner_id')
    op.drop_column('bucket', 'owner_name')
    op.create_table('file',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='file_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='file_pkey')
    )
    op.create_index('ix_file_url', 'file', ['url'], unique=True)
    op.create_index('ix_file_id', 'file', ['id'], unique=False)
    # ### end Alembic commands ###
