{
 "title": "PostgreSQL Dashboard",
 "description": "PostgreSQL dashboard example",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Bucket Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Buckets",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT id, bucket_name, created_at, owner_name, owner_id, updated_at FROM public.bucket ORDER BY created_at DESC"
    }
   ]
  },
  {
   "title": "Number of Buckets (Last 30 Days)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('day', created_at) as time, count(*) FROM public.bucket WHERE created_at >= NOW() - INTERVAL '30 days' GROUP BY 1 ORDER BY 1"
    }
   ]
  },
  {
   "title": "Buckets per Owner",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT owner_name, count(*) FROM public.bucket GROUP BY owner_name"
    }
   ]
  }
 ]
}